"""empty message

Revision ID: 2b085f85930b
Revises: 5d55ca6a1ce1
Create Date: 2020-10-03 23:30:31.020254

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2b085f85930b'
down_revision = '5d55ca6a1ce1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'completed')
    op.drop_column('tasks', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('user_id', mysql.VARCHAR(length=150), nullable=False))
    op.add_column('tasks', sa.Column('completed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
