"""empty message

Revision ID: 834cf468d25f
Revises: 2b085f85930b
Create Date: 2020-10-03 23:36:38.888147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '834cf468d25f'
down_revision = '2b085f85930b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('completed', sa.Boolean(), nullable=False))
    op.add_column('tasks', sa.Column('user_id', sa.String(length=150), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'user_id')
    op.drop_column('tasks', 'completed')
    # ### end Alembic commands ###
